/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;


/**
 *
 * @author Windows HD
 */
public class DodavanjePolaznika extends javax.swing.JDialog {

    /**
     * Creates new form Dodavanje
     */
    public DodavanjePolaznika(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(2147483647, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(573, 50));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dodavanje polaznika");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.setLayout(new java.awt.GridLayout(6, 0, 0, 20));

        jLabel3.setText("Ime:");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel3.add(jLabel3);

        jTextField1.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField1);

        jLabel4.setText("Prezime:");
        jPanel3.add(jLabel4);

        jTextField7.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField7.setMinimumSize(new java.awt.Dimension(64, 20));
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField7);

        jLabel5.setText("Email:");
        jPanel3.add(jLabel5);

        jTextField8.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField8.setMinimumSize(new java.awt.Dimension(64, 20));
        jTextField8.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField8);

        jLabel6.setText("Broj telefona:");
        jPanel3.add(jLabel6);

        jTextField9.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField9.setMinimumSize(new java.awt.Dimension(64, 20));
        jTextField9.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField9);

        jLabel7.setText("Datum rodjenja:");
        jPanel3.add(jLabel7);

        jTextField10.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField10.setMinimumSize(new java.awt.Dimension(64, 20));
        jTextField10.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField10);

        jLabel8.setText("Kategorija:");
        jPanel3.add(jLabel8);

        jTextField11.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField11.setMinimumSize(new java.awt.Dimension(64, 20));
        jTextField11.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField11);

        getContentPane().add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(739, 100));

        jButton2.setText("Dodaj");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
