/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import broker.DatabaseConnection;
import domen.Polaznik;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroleri.KontrolerPolaznik;

/**
 *
 * @author Windows HD
 */
public class Glavna extends javax.swing.JFrame {

    /**
     * Creates new form Glavna
     */
    public Glavna() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public Glavna(String korisnickoIme) throws SQLException{
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lblInstruktor.setText(korisnickoIme);
        
        List<Polaznik> polaznici = KontrolerPolaznik.getList();
        for(Polaznik p : polaznici){
            cmbPolaznik.addItem(p);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblInstruktor = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmbPolaznik = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBrTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDatRodj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtKategorija = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPlanObuke = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCenaObuke = new javax.swing.JTextField();
        btnObrisiPolaznik = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        meniNalog = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(565, 50));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 20, 15));

        jLabel1.setText("Dobrodosao/la");
        jPanel2.add(jLabel1);

        lblInstruktor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInstruktor.setText("username");
        jPanel2.add(lblInstruktor);
        jPanel2.add(filler1);

        jPanel1.add(jPanel2);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Redni broj", "Datum casa", "Trajanje casa", "Cena casa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);

        jPanel5.setMaximumSize(new java.awt.Dimension(325, 32767));
        jPanel5.setPreferredSize(new java.awt.Dimension(325, 423));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setPreferredSize(new java.awt.Dimension(325, 400));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        cmbPolaznik.setMaximumSize(new java.awt.Dimension(300, 32767));
        cmbPolaznik.setMinimumSize(new java.awt.Dimension(300, 22));
        cmbPolaznik.setPreferredSize(new java.awt.Dimension(300, 22));
        cmbPolaznik.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPolaznikItemStateChanged(evt);
            }
        });
        cmbPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPolaznikActionPerformed(evt);
            }
        });
        jPanel3.add(cmbPolaznik);

        jLabel3.setText("Ime:");
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel3);

        txtIme.setEditable(false);
        txtIme.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtIme);

        jLabel4.setText("Prezime:");
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel4);

        txtPrezime.setEditable(false);
        txtPrezime.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtPrezime);

        jLabel5.setText("Email:");
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel5);

        txtEmail.setEditable(false);
        txtEmail.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtEmail);

        jLabel6.setText("Broj telefona:");
        jLabel6.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel6);

        txtBrTel.setEditable(false);
        txtBrTel.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtBrTel);

        jLabel7.setText("Datum rodjenja:");
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel7);

        txtDatRodj.setEditable(false);
        txtDatRodj.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtDatRodj);

        jLabel8.setText("Kategorija:");
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel8);

        txtKategorija.setEditable(false);
        txtKategorija.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtKategorija);

        jLabel9.setText("Plan obuke:");
        jLabel9.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel9);

        txtPlanObuke.setEditable(false);
        txtPlanObuke.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtPlanObuke);

        jLabel10.setText("Cena obuke:");
        jLabel10.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel3.add(jLabel10);

        txtCenaObuke.setEditable(false);
        txtCenaObuke.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(txtCenaObuke);

        btnObrisiPolaznik.setForeground(new java.awt.Color(255, 51, 51));
        btnObrisiPolaznik.setText("Obrisi polaznika");
        btnObrisiPolaznik.setPreferredSize(new java.awt.Dimension(250, 45));
        btnObrisiPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPolaznikActionPerformed(evt);
            }
        });
        jPanel3.add(btnObrisiPolaznik);

        jPanel5.add(jPanel3);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout1);

        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Obrisi cas");
        jButton5.setEnabled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(250, 45));
        jPanel6.add(jButton5);

        jPanel5.add(jPanel6);

        jPanel4.add(jPanel5);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Kreiraj");

        jMenuItem1.setText("Polaznik");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Instruktor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Cas");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Izmeni");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Polaznik");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Instruktor");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Cas");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        meniNalog.setText("Nalog");

        jMenuItem8.setText("prikazi");
        meniNalog.add(jMenuItem8);

        jMenuItem9.setText("odjavite se");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        meniNalog.add(jMenuItem9);

        jMenuBar1.add(meniNalog);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            new DodavanjePolaznika(this, true).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cmbPolaznikItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPolaznikItemStateChanged
        Polaznik p = (Polaznik) cmbPolaznik.getSelectedItem();
        txtIme.setText(p.getIme());
        txtPrezime.setText(p.getPrezime());
        txtEmail.setText(p.getEmail());
        txtBrTel.setText(p.getBrojTelefona());
        txtDatRodj.setText(p.getDatumRodjenja().toString());
        txtKategorija.setText(p.getKategorija().getNaziv());
        
    }//GEN-LAST:event_cmbPolaznikItemStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new Registracija().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnObrisiPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPolaznikActionPerformed
        try {
            Polaznik p = (Polaznik) cmbPolaznik.getSelectedItem();
            Object[] opcije = {"Da", "Ne"};
            int izbor = JOptionPane.showOptionDialog(this,"Da li sigurno zelite da obrisete polaznika "
                    +p.getIme()+" "+p.getPrezime()+"?","Dodavanje polaznika",
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcije,opcije[1]);

            if(izbor == JOptionPane.YES_OPTION){
                Connection conn = DatabaseConnection.getInstance();
                Statement st = conn.createStatement();
                String query = "DELETE FROM polaznik WHERE id="+p.getId();
                st.executeUpdate(query);
                st.close();
                cmbPolaznik.removeItem(p);
                JOptionPane.showMessageDialog(null, "Polaznik "+p.getIme()+" "+p.getPrezime() +" uspesno obrisan.","Brisanje polaznika",JOptionPane.INFORMATION_MESSAGE);
            }

            
        } catch (SQLException ex) {
            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObrisiPolaznikActionPerformed

    private void cmbPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPolaznikActionPerformed

    }//GEN-LAST:event_cmbPolaznikActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            new IzmenaPolaznika(this, true).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiPolaznik;
    private javax.swing.JComboBox<Polaznik> cmbPolaznik;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInstruktor;
    private javax.swing.JMenu meniNalog;
    private javax.swing.JTextField txtBrTel;
    private javax.swing.JTextField txtCenaObuke;
    private javax.swing.JTextField txtDatRodj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKategorija;
    private javax.swing.JTextField txtPlanObuke;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
